### ISSUE TITLE
Picker not handling AM/PM correctly

### ISSUE THREAD

**Issue by swbradshaw** [ugurtekbas/dialTimePicker#10]
The picker assumes the time is based on the current time, and it is not. The problem I'm seeing is calling setTime with 11:15, results in 11:15pm if the current time is PM. If the current time is AM, the picker shows 11:15am.  The reality is I have a time stored (11:15am) that I want the user to adjust.

`this.amPm` is set in the contructor and is based on the current time.  This is fine for init, but it also needs to be set in `setTime()` method.  It might make sense to overload setTime() to take in a Calendar or DateTime object.

Let me know if you need any more information.

**Comment by ugurtekbas** [comment]
Hi @swbradshaw,
Thanks for the info. I totally share your angle on this issue. If device isn't using 24 hour format, setTime() function (initTime() in other words) can't handle the time correctly.
Lets be more specific with an example:
When its pm and we want to set the time for 09:00, it shows it as 09:00pm
When its am and we want to set the time for 23:00,  it shows it as 11:00am

I will fix it as soon as possible.

**Comment by swbradsh** [comment]
@ugurtekbas - I submitted a Pull Request for this issue.  I'm not sure if it handles all the scenarios, but it fixed the issue I was having.

**Comment by ugurtekbas** [comment]
@swbradsh Unfortunately it doesn't handles the issues cases.
You can check c30b8d5 , it fixes this issue and adds few more things.

Cheers
