### ISSUE TITLE
Set a fixed date and time

### ISSUE THREAD

**Issue by paragones** [ugurtekbas/dialTimePicker#2]
Hi, 

Nice time picker! Is is possible to set a specific time and date from the beginning?

**Comment by ugurtekbas** [comment]
Hi @paragones ,
That also looks like a nice feature to have, I'll try to implement it as soon as I have some time.

**Comment by ezebongiovi** [comment]
Hi @ugurtekbas,
I'm using this library in a personal proyect, I was needing this feature so I created it in a `CustomPicker` by copying your `Picker`'s code. But then I thought I could contribute with that feature fixing this issue. So if you can give me access for creating a `branch` and making a `PullRequest` I would contribute, if not don't worry give you the snippet here.

**Picker.onDraw() : 146**
```
if (firstRun){
            setFirstTime(getTime());
```
**Picker.setFirstTime() : 205**
```
public void setFirstTime(@NonNull final Date initialDate){
        int firstHour;
        final Calendar cal = Calendar.getInstance();
        cal.setTime(initialDate);
```

**USAGE**
`picker.setFirstTime(mInitialDate)`
