### ISSUE TITLE
Set TimePicker Minutes always not get the correct minutesCount.

### ISSUE THREAD

**Issue by ahmedmoussa8** [ugurtekbas/dialTimePicker#9]
I want to thank you for this effort on this library.
When i try to set minutes and hours for the picker programmatically  the minutes never get the exact number.
Lets say i have a string variable:
`String time = "10:45"`
`List<Integer> getHoursAndMinutes(String time) {
        int hours = 0, minutes = 0;
        List<Integer> timingList = new ArrayList<>();
        try {
            String[] separated = time.replaceAll(" ", "").split(":");
            hours = Integer.valueOf(separated[0]);
            minutes = Integer.valueOf(separated[1]) ;
            timingList.add(hours);
            timingList.add(minutes);

```
    } catch (Exception e) {
        e.printStackTrace();
    }
    return timingList;
}`
```

`timePicker = (Picker) findViewById(R.id.timePicker);
        timePicker.setHourFormat(true);`
`timePicker.setTime(
                        getHoursAndMinutes(time.replaceAll(" ", "")).get(0),
                        getHoursAndMinutes(time.replaceAll(" ", "")).get(1)
                );`
So the timer minutes never get the exact 45 min.
Any Help ?
Thanks.

**Comment by ugurtekbas** [comment]
Hi @g88k, 

Thanks for the heads up. This was a calculation bug which accours while rounding result of "degree" related calculation.
With this commit it doesn't need to calculate minutes if it is set programmatically.
You can check out the comment lines.

Cheers
